export const SCENARIO_MATRIX = [
  {
    id: 'AS-01', acs: ['T4-AC2', 'T4-AC3', 'T4-AC6', 'T4-AC8', 'T4R-AC1'],
    setup: 'A fresh isolated target receives literal git init and proves unborn symbolic HEAD, absent index and branch ref, no commit, and zero tracked files before using the locally built scoped 0.1.0 release.',
    expectedDecision: 'READY then success with the fixed payload, one managed block, six profiles, verified state, no sentinel, and byte-identical .git metadata.',
    primaryEvidence: 'Git symbolic-ref/rev-parse/ls-files assertions and pre/post .git tree hashes accompany exact release bytes, marker scan, six profiles, installer identity, and verified state.',
    failureSignals: 'IO_UNAVAILABLE, dirty-overlap bypass, Git metadata mutation, a commit/index/tracked file, missing payload, wrong scoped identity, wrong profile count, or retained sentinel.',
  },
  {
    id: 'AS-02', acs: ['T4-AC2', 'T4-AC3'],
    setup: 'A large CRLF target-owned AGENTS.md containing 12,000 deterministic rule rows.',
    expectedDecision: 'READY then success with exactly one managed interval and byte-identical outer content.',
    primaryEvidence: 'Byte comparison of the marker scanner prefix to the original large file and exact marker counts.',
    failureSignals: 'Any changed outer byte, duplicate marker, missing marker, or managed interval mismatch.',
  },
  {
    id: 'AS-03', acs: ['T4-AC2', 'T4-AC3', 'T4-AC5'],
    setup: 'Synthetic target-owned agents, skill, plugin, script, CI, and opaque adjacent content outside planned Harness paths.',
    expectedDecision: 'READY then success confined to exact release paths, AGENTS.md, and state without inspecting or changing adjacent content.',
    primaryEvidence: 'Lifecycle filesystem-event path allowlist, exact changed-report allowlist, and byte-identical AGENTS.md outer content.',
    failureSignals: 'Adjacent-content access event, changed outer byte, or reported change outside the exact lifecycle write surface.',
  },
  {
    id: 'AS-04', acs: ['T4-AC2', 'T4-AC3'],
    setup: 'A clean same-version installed target, including its original state timestamps.',
    expectedDecision: 'Both install and update return NO_OP and change no payload, block, state byte, or timestamp.',
    primaryEvidence: 'Whole synthetic-target tree snapshot and exact state-byte comparisons around both plans.',
    failureSignals: 'READY/CONFLICT decision, changed tree hash, or changed canonical state bytes.',
  },
  {
    id: 'AS-05', acs: ['T4-AC2', 'T4-AC3'],
    setup: 'A clean 0.1.0 install and synthetic 0.2.0 release with one replacement, one removal, and one required new path.',
    expectedDecision: 'READY with exact replace/remove/create asymmetry, followed by verified 0.2.0 state and references.',
    primaryEvidence: 'Exact plan arrays, resulting bytes/absence, marker/reference checks, and installedVersion assertion.',
    failureSignals: 'Wrong action classification, missing/extra changed path, stale bytes, stale file, or stale state version.',
  },
  {
    id: 'AS-06', acs: ['T4-AC2', 'T4-AC3'],
    setup: 'One modified state-owned file followed by a release replacement and an explicit decline/confirm sequence.',
    expectedDecision: 'Modification and deterministic backup are disclosed; decline writes nothing; confirmation writes/verifies backup before mutation and again before success.',
    primaryEvidence: 'Plan disclosure, exact backup bytes, ordered filesystem events, successful replacement, and deleted-backup non-recreation on no-op.',
    failureSignals: 'Undisclosed drift, mutation before backup verification, backup mismatch, no second verification, or backup recreation after user deletion.',
  },
  {
    id: 'AS-07', acs: ['T4-AC2', 'T4-AC3'],
    setup: 'Separate unmanaged namespace, unowned prefixed profile, exact dirty overlap, and update-new-path collision fixtures.',
    expectedDecision: 'Each fixture stops as INCOMPLETE_OR_UNOWNED or CONFLICT with zero writes and no adoption/replacement.',
    primaryEvidence: 'Path-specific conflict codes and byte/hash snapshots before and after each plan.',
    failureSignals: 'READY/NO_OP, any tree mutation, missing collision path, or target-owned content replacement.',
  },
  {
    id: 'AS-08', acs: ['T4-AC2', 'T4-AC3'],
    setup: 'Missing-half, duplicate, nested, reversed, damaged, and unowned/lookalike marker byte fixtures.',
    expectedDecision: 'Every case is terminal INVALID_MANAGED_MARKER with byte-identical AGENTS.md, even when confirmed.',
    primaryEvidence: 'Per-variant conflict list, confirmed run exit, exact bytes, and absence of IO_UNAVAILABLE.',
    failureSignals: 'Repair/normalization, derivative IO_UNAVAILABLE, changed bytes, or confirmation bypass.',
  },
  {
    id: 'AS-09', acs: ['T4-AC2', 'T4-AC3'],
    setup: 'Installed target with target-owned content and drift requiring backup, plus an injected final state-delete failure fixture.',
    expectedDecision: 'Successful uninstall removes only state-owned payload/block, preserves target content/backups, and removes state last; injected final delete reports failure.',
    primaryEvidence: 'Ordered mutation events, exact preserved bytes, state/payload absence, backup survival, and non-success failure report.',
    failureSignals: 'Target-content loss, backup loss, early state deletion, retained successful state, or false success on injected failure.',
  },
  {
    id: 'AS-10', acs: ['T4-AC2', 'T4-AC4', 'T4-AC7'],
    setup: 'A structurally valid installed target whose outer AGENTS.md prefix has exactly one changed byte.',
    expectedDecision: 'Payload, TOML/profile, route/reference, block, and state checks pass, outer-byte verification fails, and overall result is FAIL.',
    primaryEvidence: 'Named structural booleans all true, outerBytes false, and overall false.',
    failureSignals: 'Structural fixture fails before the counterexample or overall passes despite outer-byte drift.',
  },
  {
    id: 'AS-11', acs: ['T4-AC2', 'T4-AC3'],
    setup: 'Empty, absolute, NUL, traversal, symlink-parent, regular-file parent, FIFO parent, and confirmed/force bypass attempts.',
    expectedDecision: 'Every unsafe path/type stops before outside-root access or mutation; confirmation and unsupported force cannot bypass.',
    primaryEvidence: 'Thrown UNSAFE_PATH/CONFLICT decisions, outside canary bytes, filesystem events, and CLI force usage rejection.',
    failureSignals: 'Outside event or canary change, READY plan, accepted force flag, or confirmed mutation.',
  },
  {
    id: 'AS-12', acs: ['T4-AC2', 'T4-AC3'],
    setup: 'A modified managed update with a capturable payload-write fault after backup/sentinel publication.',
    expectedDecision: 'Success is withheld; report distinguishes changed/unchanged paths, preserves exact backup/evidence, and next invocation stops unhealthy.',
    primaryEvidence: 'Nonzero lifecycle result, false success report, unchanged replacement path, exact backup, present sentinel, and follow-up INCOMPLETE_OR_UNOWNED.',
    failureSignals: 'Success, missing/mismatched backup, false changed-path claim, absent incomplete evidence, or follow-up READY.',
  },
];
